# Split transport configuration (dongle / central)
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_KEYBOARD_NAME="T23MX-D v1"
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
